# Generated by Django 5.0.4 on 2024-08-26 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('pub_date', models.DateField()),
                ('comment_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('create_account', models.BooleanField(default=False)),
                ('account_password', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_different', models.BooleanField(default=False)),
                ('order_notes', models.TextField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=5)),
                ('paid_status', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('product_status', models.CharField(choices=[('PROCESS', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('qty', models.IntegerField(default=0)),
                ('product_status', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default='1.99', max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriApp.cartorder')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('min_price', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('max_price', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('produc_status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISABLED', 'Disable'), ('REVIEW', 'Review'), ('PUBLISHED', 'Publish')], default='processing', max_length=20)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '⭐☆'), (2, '⭐⭐☆☆'), (3, '⭐⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐☆☆☆☆☆')], default=0, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='agriApp.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agriApp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('image2', models.ImageField(default=0, null=True, upload_to='product_images/')),
                ('image3', models.ImageField(default=0, null=True, upload_to='product_images/')),
                ('thumbnail', models.ImageField(upload_to='product_thumbnails/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agriApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '⭐☆'), (2, '⭐⭐☆☆'), (3, '⭐⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐☆☆☆☆☆')], default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_images/')),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('address', models.CharField(default='Monrovia', max_length=255)),
                ('contact', models.CharField(default='(+231779005985)', max_length=20)),
                ('cart_resp_time', models.IntegerField()),
                ('shipping_on_time', models.BooleanField(default=True)),
                ('authentic_rating', models.DecimalField(decimal_places=2, default='100', max_digits=3)),
                ('day_return', models.CharField(default='100', max_length=100)),
                ('wyt_period', models.CharField(default='100', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agriApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
