# Generated by Django 5.0.4 on 2024-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0003_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
