# Generated by Django 5.0.4 on 2024-05-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0006_product_max_price_product_min_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('pub_date', models.DateField()),
                ('comment_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content_url', models.URLField()),
            ],
        ),
    ]
