# Generated by Django 5.0.4 on 2024-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0008_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image2',
            field=models.ImageField(default=0, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image3',
            field=models.ImageField(default=0, null=True, upload_to='product_images/'),
        ),
    ]
